### ISSUE TITLE
Add an option to be able to test the bot locally without posting into the scams room

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#10]
Some people invite it to experiment with it - you could need this as well.

Posts related to experimentation should not be cross-posted to the scam rooms as some may interpret it as abuse and place a global ban on the moderator playing with it.

**Comment by bkil** [comment]
See also #11

**Comment by jjj333-p** [comment]
looking back through old issues, this is just simply a bad idea. 

Its already risky enough having the keywords listed publicly in github, we dont want scammers and whatnot to be able to test against the bot with basically 0 effort.

closing as a wontfix.
