### ISSUE TITLE
Aggregate the rooms of occurrence per abuser

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#13]
At present, the bot outputs a separate entry for each abuser.

In our ban reason, I mention all major rooms where the abuse happened. If I just blindly copy & paste these warnings, I will keep rewriting the rule for the user, thus losing the past list of abuse for him.

Hence it would be useful if the bot either replied to its previous warning for the same user, or if it edited the past warning to add new rooms there.

**Comment by jjj333-p** [comment]
this is definitely something to think of, but *not at all* a priority

**Comment by jjj333-p** [comment]
okay so it would be incredibly hard to do editing, or reply in a way that makes sense, but i could perhaps store a list of previous rooms and express this in the log

**Comment by jjj333-p** [comment]
i forgot to close this issue, but this has been fixed as of recent updates. i need to work on documentation and finalize it into a stable release though.
