### ISSUE TITLE
Only accept commands in the commands room

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#15]
* At present, anyone could get your bot banned by manually invite it or commanding it towards a high number of rooms (or just a few with a trigger-happy moderator)
* As an easy workaround, only accept bot commands within its designated command room
* You may leave the room public while it is not abused, but as a benefit, you would see where it is commanded to and by whom (and ban those who abuse this right and/or make the room invite-only later on)

**Comment by jjj333-p** [comment]
i hadnt thought about it at the time, but this would actually make a lot of sense, because i can ban the person from adding the bot by banning them from the room, and that makes everything easier

**Comment by jjj333-p** [comment]
complete
----> https://github.com/jjj333-p/spam-police/commit/bdc1b6ef37b4aee418bf62fec42291f158ce2bce
----> https://github.com/jjj333-p/spam-police/commit/2afb2d686fec1fb603a5f953b1df67f28556276f
