### ISSUE TITLE
New bot command to identify the bot

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#16]
* At present, it only introduces itself in the initial post
* Provide an option for the bot to identify itself when queried (ideally by a moderator later on, but at present just by anyone).
* As a simple implementation, it could always reply when @mentioned.

**Comment by bkil** [comment]
The text should explain that if joining was unwanted, the operator should be contacted (within the support room?) and/or that it can be kicked. 

But effective abuse control through kicking requires that it also mentions kicking in the control room, and that would be additional complexity. #17 #18

**Comment by jjj333-p** [comment]
the bot should now respond to mentions --> https://github.com/jjj333-p/spam-police/commit/bf102429968f79c1ed36a1bd9cb6d92ed28604ad
