### ISSUE TITLE
If the bot is kicked, record this fact in a database of rooms to avoid

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#18]
Related #17

**Comment by jjj333-p** [comment]
could make the +leave cmd work for people other than just me, also clean up that code

**Comment by jjj333-p** [comment]
so some investigating, it would take more work to tell if it was kicked v.s. just me making it leave, however i suppose if i made it leave from a room then it should also blacklist that room

**Comment by jjj333-p** [comment]
okay this has been implemented, the only thing left to do is make a blacklist command for admins, but the first thing i have to do is add a config for admin users
