### ISSUE TITLE
Improve introduction text

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#19]
The text (#16 ) should explain that if joining was unwanted, the operator should be contacted (within the support room?) and/or that it can be kicked. 

But effective abuse control through kicking requires that it also mentions kicking in the control room, and that would be additional complexity.

**Comment by jjj333-p** [comment]
if this is apart of #16 post it on #16 for fucks sake

**Comment by bkil** [comment]
You have an introduction text already, hence why I thought you would want to factor this out, but however you wish.
